### PR TITLE
added new testVerifySymbol

### PR DESCRIPTION
**Pull request by morozanna503**
added new testVerifySymbol

### CODE REVIEW

**Review by matsstang — COMMENTED** [review]
you have to change 132-134
there has to be:
ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--remote-allow-origins=*", "--headless", "--window-size=1920,1080");
        WebDriver driver = new ChromeDriver(chromeOptions);

CI doesn't work without this

**Review by matsstang — COMMENTED** [review]
in 136 you have to put chromeOptions into ChromeDriver:
WebDriver driver = new ChromeDriver(chromeOptions);

**Review by matsstang — APPROVED** [review]

**Comment by morozanna503** [comment]
> in 136 you have to put chromeOptions into ChromeDriver: WebDriver driver = new ChromeDriver(chromeOptions);

Thanks for your notes. fixed this

**Review by IrynaHryhoriv — APPROVED** [review]

**Comment by matsstang** [comment]
you have to merge pull request

**Comment by matsstang** [comment]
you have to merge your pull request

**Pull request closed without merging**
