### PR TITLE
Sh/first test

### PR DESCRIPTION
**Pull request by SvetlanaHoshaw**

### CODE REVIEW

**Review by matsstang — APPROVED** [review]

**Review by GelikaUS — APPROVED** [review]
Approved

**Comment by matsstang** [comment]
you have to merge pull request

**Comment by SvetlanaHoshaw** [comment]
> 

I merged it, but I don't see my test in the main branch

**Comment by matsstang** [comment]
did you update main branch?

**Comment by SvetlanaHoshaw** [comment]
Do you mean pull changes into my local branch? I do not see my test in the main branch of GitHub. How can I update the main branch in GitHub in order to see my PR?

**Comment by matsstang** [comment]
in what class you've made changes?

**Comment by SvetlanaHoshaw** [comment]
In class I've created "SvetlanaGroupFuOpyatJavaTest"

**Comment by matsstang** [comment]
I believe it happened because you've deleted class
SvetlanaGroupFuOpyatJavaTest
It's not exists on the project

**Comment by SvetlanaHoshaw** [comment]
I was trying to delete previous unsuccessful commits and probably class was deleted. Also, I can't pull changes from GitHub to my local git. It says:  "Git Pull Failed.  Your local changes will be overwritten by merge. Commit, stash, or revert them to proceed."
I don't see how to accept my changes to be overwritten

**Comment by SvetlanaHoshaw** [comment]
I was able to pull changes from GitHub. Wil try to create a new PR. Thank you for your help

**Comment by matsstang** [comment]
try to make new branch from main
merge main into it
and try again to update main and commit

**Comment by SvetlanaHoshaw** [comment]
Done! Thank you so much for help and approve, hope it will be successful this time

**Comment by matsstang** [comment]
👍

**Pull request merged**
