### PR TITLE
AT 13.01 | Footer > Verify Jenkins version | add 5 tests

### PR DESCRIPTION
**Pull request by AnaZaleski**
https://trello.com/c/ltDZH2i8
https://trello.com/c/1iHxZgT3
https://trello.com/c/2HKsM0pi
https://trello.com/c/3JiUdfW4
https://trello.com/c/5wrPAdTd

### CODE REVIEW

**Comment by AnaZaleski** [comment]
[AT 13.01 | Footer > Verify Jenkins version on My Views Page](https://trello.com/c/5wrPAdTd/495-at-1301-footer-verify-jenkins-version-on-my-views-page)

**Comment by AnaZaleski** [comment]
[AT 13.01 | Footer > Verify Jenkins version on Home Page](https://trello.com/c/ltDZH2i8/492-at-1301-footer-verify-jenkins-version-on-home-page)

**Comment by AnaZaleski** [comment]
[AT 13.01 | Footer > Verify Jenkins version on People Page](https://trello.com/c/1iHxZgT3/493-at-1301-footer-verify-jenkins-version-on-people-page)

**Comment by AnaZaleski** [comment]
[AT 13.01 | Footer > Verify Jenkins version on Build History Page](https://trello.com/c/2HKsM0pi/496-at-1301-footer-verify-jenkins-version-on-build-history-page)

**Comment by AnaZaleski** [comment]
[AT 13.01 | Footer > Verify Jenkins version on Manage Jenkins Page](https://trello.com/c/3JiUdfW4/494-at-1301-footer-verify-jenkins-version-on-manage-jenkins-page)

**Review by GelikaUS — APPROVED** [review]

**Pull request merged**
