### PR TITLE
RF | ConsoleOutputPage > add FindBy

### PR DESCRIPTION
**Pull request by nikabenz**
https://trello.com/c/oYK7XZBq

### CODE REVIEW

**Comment by nikabenz** [comment]
[RF | ConsoleOutputPage > add FindBy](https://trello.com/c/oYK7XZBq/2000-rf-consoleoutputpage-add-findby)

**Review by judmi — COMMENTED** [review]
There's no need in blank lines after a method header in methods with only return statement in the body

**Review by nikabenz — COMMENTED** [review]
**The blank lines were deleted** (after a method header in methods with only return statement in the body)

**Review by judmi — APPROVED** [review]
Looking good now!

**Review by NataliaKubiak — APPROVED** [review]

**Pull request merged**
