### PR TITLE
RF_08_03_AddDescriptionForBuild

### PR DESCRIPTION
**Pull request by PratasevichSerge**
RF - https://trello.com/c/hqOqsKNa

### CODE REVIEW

**Review by Maksim2404 — APPROVED** [review]
We were making this test more reliable and robust, especially with the "Chevron drop-down" element

**Review by TinaQA — APPROVED** [review]

**Review by KathyGU — COMMENTED** [review]
1. DROP_DOWN_SERIAL_NUMBER XPath could be way shorter. Why do you refer to class attribute in <a> tag when the different attribute could be used? So that your DROP_DOWN_SERIAL_NUMBER XPath would be looked like as "//a[@href='/job/" + NAME_PIPELINE + "/1/']/button". 
2. Also you use too much wait commands. 
3. SERIAL_NUMBER_OF_BUILD - you try to find this element two times in a row (lines 60 - 61) and it's not correct to do so. 
4. Same mistake you make when trying to find  DROP_DOWN_SERIAL_NUMBER - you also do this two times in a row (lines 63 and 66). 
I would recomend you to figure out a different solution to locate  the DROP_DOWN_SERIAL_NUMBER element given my comments above.
I would also correct EDIT_BUILD_INFORMATION xpath.

**Comment by Maksim2404** [comment]
> 1. DROP_DOWN_SERIAL_NUMBER XPath could be way shorter. Why do you refer to class attribute in  tag when the different attribute could be used? So that your DROP_DOWN_SERIAL_NUMBER XPath would be looked like as "//a[@href='/job/" + NAME_PIPELINE + "/1/']/button".
> 2. Also you use too much wait commands.
> 3. SERIAL_NUMBER_OF_BUILD - you try to find this element two times in a row (lines 60 - 61) and it's not correct to do so.
> 4. Same mistake you make when trying to find  DROP_DOWN_SERIAL_NUMBER - you also do this two times in a row (lines 63 and 66).
> 5. Same issue with EDIT_BUILD_INFORMATION  - you locate it 2 times in a row.
> 
> To sum up: there are THREE elements you r trying to locate twice using wait commands. It does not make a good code. Please try to figure out a different solution to locate and interact with the above mentioned elements.

**Comment by Maksim2404** [comment]
@KathyGU In my pow,  I'd say in the case of bullet 3,4,5 he double checked those elements are clickable or they can be visible, and after He makes sure that it robust elements he is starting using them like by Actions class, etc. I'd say he's right in some ways

**Comment by KathyGU** [comment]
@Maksim2404 I understand completely what Serge intends to do, but the way he is doing this is not correct.

**Comment by KathyGU** [comment]
@Maksim2404 @PratasevichSerge  in order not to sound like an evil criticising gnome, I wrote - and I hope you don't mind - my version of the test in your class) Please, note I made adjustments to some Xpathes, specifically to DESCRIPTION_TEXT - to locate the  element you used CSS, but in order to stick to the rules of uniformity I think it's better to use xpath rather than Css locator. Here is my pr https://github.com/RedRoverSchool/JenkinsQA_06/pull/2019 )

**Comment by Maksim2404** [comment]
@KathyGU In my view, you're using  JavaScriptExecutor in your code to click on a particular element which is not recommended to do. And in Slack there're a bunch of dialogs about how to handle this, for ex using Actions and clicking Enter.

**Comment by Maksim2404** [comment]
And also, I didn't get the sense of rewriting the same test in one class. now we have a conflict in this class.

**Comment by KathyGU** [comment]
@Maksim2404 There are several methods to locate and interact with the elements in Selenium and it is up to tester which to use. The key issue of Serge's test is that he locates each of three elements twice which is hardly expectable.

**Pull request closed without merging**
