### PR TITLE
fix training test -Sergi

### PR DESCRIPTION
**Pull request by SergiKarpfen**

### CODE REVIEW

**Comment by judmi** [comment]
If you are using webdriverwait you don't need to use thread.sleep's
And also you don't need to quit driver as it's done in the aftermethod anyway

**Comment by SergiKarpfen** [comment]
> If you are using webdriverwait you don't need to use thread.sleep's And also you don't need to quit driver as it's done in the aftermethod anyway

My mistake here. So, do I have to cancel my PR now?

**Comment by Native1331** [comment]
Доброе утро! А getDriver().quit() зачем?)

**Comment by Native1331** [comment]
> > If you are using webdriverwait you don't need to use thread.sleep's And also you don't need to quit driver as it's done in the aftermethod anyway
> 
> My mistake here. So, do I have to cancel my PR now?

No, you dont have to csncel your PR, just make changes, commit and push🙂

**Pull request closed without merging**
